
import os
import psycopg2
from dotenv import load_dotenv

# Load .env manually if not running in Docker
# Assumes .env is in current directory
if os.path.exists('.env'):
    load_dotenv('.env')

DB_HOST = os.getenv("POSTGRES_HOST", "localhost")
DB_USER = os.getenv("POSTGRES_USER", "postgres")
DB_PASS = os.getenv("POSTGRES_PASSWORD", "password")
DB_NAME = os.getenv("POSTGRES_DB", "webmusic")
DB_PORT = os.getenv("POSTGRES_PORT", "5432")

def setup_database():
    print(f"Connecting to Database {DB_HOST}:{DB_PORT}...")
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            user=DB_USER,
            password=DB_PASS,
            dbname=DB_NAME,
            port=DB_PORT
        )
        conn.autocommit = True
        cur = conn.cursor()

        print("Checking/Creating 'Lyrics' table...")
        
        # Create Table SQL
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS "Lyrics" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "MediaFileId" integer NOT NULL,
            "Content" text NOT NULL,
            "Language" text NOT NULL DEFAULT 'unknown',
            "Source" text NOT NULL DEFAULT 'AI',
            "Version" text NOT NULL DEFAULT 'v1',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
            CONSTRAINT "PK_Lyrics" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Lyrics_MediaFiles_MediaFileId" FOREIGN KEY ("MediaFileId") 
                REFERENCES "MediaFiles" ("Id") ON DELETE CASCADE
        );
        """
        cur.execute(create_table_sql)

        # Create Index SQL
        create_index_sql = """
        CREATE INDEX IF NOT EXISTS "IX_Lyrics_MediaFileId" ON "Lyrics" ("MediaFileId");
        """
        cur.execute(create_index_sql)

        print("Success! Database schema for Lyrics is ready.")
        
        cur.close()
        conn.close()

    except Exception as e:
        print(f"Error updating database: {e}")
        print("Tip: Ensure the database container is running and .env is correct.")

if __name__ == "__main__":
    setup_database()
