--
-- PostgreSQL database dump
--

\restrict LCbKjUjoKzFdaFw9Cvf42E8OzxltTgSXKLqh8nc2OeLpDbDtCLSdNlEaaI2SvnR

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: EnrichmentAttempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EnrichmentAttempts" (
    "Id" integer NOT NULL,
    "JobId" text NOT NULL,
    "MediaFileId" integer NOT NULL,
    "Provider" text NOT NULL,
    "RequestKey" text,
    "HTTPStatus" integer,
    "Outcome" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "RetryCount" integer NOT NULL,
    "Detail" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."EnrichmentAttempts" OWNER TO postgres;

--
-- Name: EnrichmentAttempts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EnrichmentAttempts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EnrichmentAttempts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EnrichmentJobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EnrichmentJobs" (
    "Id" text NOT NULL,
    "Scope" text NOT NULL,
    "RequestedByUserId" integer,
    "Total" integer NOT NULL,
    "Processed" integer NOT NULL,
    "Updated" integer NOT NULL,
    "Unmatched" integer NOT NULL,
    "Skipped" integer NOT NULL,
    "Failed" integer NOT NULL,
    "Cursor" integer NOT NULL,
    "Status" text NOT NULL,
    "SongIdsJson" text DEFAULT '[]'::text NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone
);


ALTER TABLE public."EnrichmentJobs" OWNER TO postgres;

--
-- Name: Favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Favorites" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Favorites" OWNER TO postgres;

--
-- Name: Favorites_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Favorites" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Favorites_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lyrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lyrics" (
    "Id" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "Content" text,
    "Language" text,
    "Source" text,
    "Version" text,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public."Lyrics" OWNER TO postgres;

--
-- Name: Lyrics_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Lyrics_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Lyrics_Id_seq" OWNER TO postgres;

--
-- Name: Lyrics_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Lyrics_Id_seq" OWNED BY public."Lyrics"."Id";


--
-- Name: MediaFiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaFiles" (
    "Id" integer NOT NULL,
    "FilePath" text NOT NULL,
    "Title" text NOT NULL,
    "Artist" text NOT NULL,
    "Album" text NOT NULL,
    "Genre" text NOT NULL,
    "Year" integer NOT NULL,
    "Duration" interval NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "FileHash" text DEFAULT ''::text NOT NULL,
    "ParentPath" text DEFAULT ''::text NOT NULL,
    "AddedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ScanSourceId" integer NOT NULL,
    "CoverArt" text
);


ALTER TABLE public."MediaFiles" OWNER TO postgres;

--
-- Name: MediaFiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MediaFiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MediaFiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MediaIdentities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaIdentities" (
    "Id" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "Provider" text NOT NULL,
    "RecordingId" text,
    "ReleaseId" text,
    "ArtistId" text,
    "ISRC" text,
    "AcoustId" text,
    "MatchMethod" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "Status" text NOT NULL,
    "MatchedAt" timestamp with time zone NOT NULL,
    "LastVerifiedAt" timestamp with time zone
);


ALTER TABLE public."MediaIdentities" OWNER TO postgres;

--
-- Name: MediaIdentities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MediaIdentities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MediaIdentities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MediaTags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaTags" (
    "Id" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "Namespace" text NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "NumericValue" double precision,
    "Confidence" double precision NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."MediaTags" OWNER TO postgres;

--
-- Name: MediaTags_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MediaTags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MediaTags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MusicEnrichments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MusicEnrichments" (
    "Id" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "Provider" text NOT NULL,
    "ExternalId" text,
    "Confidence" double precision NOT NULL,
    "Status" text NOT NULL,
    "Details" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."MusicEnrichments" OWNER TO postgres;

--
-- Name: MusicEnrichments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MusicEnrichments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MusicEnrichments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PlayHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlayHistories" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "PlayedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PlayHistories" OWNER TO postgres;

--
-- Name: PlayHistories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PlayHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlayHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PlaylistSongs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaylistSongs" (
    "Id" integer NOT NULL,
    "PlaylistId" integer NOT NULL,
    "MediaFileId" integer NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PlaylistSongs" OWNER TO postgres;

--
-- Name: PlaylistSongs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PlaylistSongs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlaylistSongs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Playlists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Playlists" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UserId" integer NOT NULL,
    "CoverArt" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Type" text DEFAULT 'normal'::text NOT NULL,
    "ShareToken" text,
    "ShareExpiresAt" timestamp with time zone,
    "SharePassword" text
);


ALTER TABLE public."Playlists" OWNER TO postgres;

--
-- Name: Playlists_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Playlists" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Playlists_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Plugins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Plugins" (
    "Id" integer NOT NULL,
    "Name" text DEFAULT ''::text NOT NULL,
    "Description" text DEFAULT ''::text,
    "BaseUrl" text DEFAULT ''::text,
    "EntryPath" text DEFAULT '/'::text,
    "Icon" text DEFAULT 'Extension'::text,
    "IsEnabled" boolean DEFAULT true,
    "CreatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."Plugins" OWNER TO postgres;

--
-- Name: Plugins_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Plugins_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Plugins_Id_seq" OWNER TO postgres;

--
-- Name: Plugins_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Plugins_Id_seq" OWNED BY public."Plugins"."Id";


--
-- Name: ScanSources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ScanSources" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Path" text NOT NULL,
    "Type" text NOT NULL,
    "StorageCredentialId" integer,
    "UserId" integer
);


ALTER TABLE public."ScanSources" OWNER TO postgres;

--
-- Name: ScanSources_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ScanSources" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ScanSources_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StorageCredentials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."StorageCredentials" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "ProviderType" text NOT NULL,
    "Host" text NOT NULL,
    "AuthData" text NOT NULL,
    "UserId" integer
);


ALTER TABLE public."StorageCredentials" OWNER TO postgres;

--
-- Name: StorageCredentials_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."StorageCredentials" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StorageCredentials_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TagEvidences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TagEvidences" (
    "Id" integer NOT NULL,
    "MediaTagId" integer NOT NULL,
    "Source" text NOT NULL,
    "SourceId" text,
    "EvidenceUrl" text,
    "EvidenceText" text,
    "RetrievedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "RawPayload" text
);


ALTER TABLE public."TagEvidences" OWNER TO postgres;

--
-- Name: TagEvidences_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TagEvidences" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TagEvidences_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "IsAdmin" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lyrics Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lyrics" ALTER COLUMN "Id" SET DEFAULT nextval('public."Lyrics_Id_seq"'::regclass);


--
-- Name: Plugins Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Plugins" ALTER COLUMN "Id" SET DEFAULT nextval('public."Plugins_Id_seq"'::regclass);


--
-- Name: EnrichmentAttempts EnrichmentAttempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EnrichmentAttempts"
    ADD CONSTRAINT "EnrichmentAttempts_pkey" PRIMARY KEY ("Id");


--
-- Name: EnrichmentJobs EnrichmentJobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EnrichmentJobs"
    ADD CONSTRAINT "EnrichmentJobs_pkey" PRIMARY KEY ("Id");


--
-- Name: Lyrics Lyrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lyrics"
    ADD CONSTRAINT "Lyrics_pkey" PRIMARY KEY ("Id");


--
-- Name: MediaIdentities MediaIdentities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaIdentities"
    ADD CONSTRAINT "MediaIdentities_pkey" PRIMARY KEY ("Id");


--
-- Name: MediaTags MediaTags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaTags"
    ADD CONSTRAINT "MediaTags_pkey" PRIMARY KEY ("Id");


--
-- Name: MusicEnrichments MusicEnrichments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MusicEnrichments"
    ADD CONSTRAINT "MusicEnrichments_pkey" PRIMARY KEY ("Id");


--
-- Name: Favorites PK_Favorites; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id");


--
-- Name: MediaFiles PK_MediaFiles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "PK_MediaFiles" PRIMARY KEY ("Id");


--
-- Name: PlayHistories PK_PlayHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlayHistories"
    ADD CONSTRAINT "PK_PlayHistories" PRIMARY KEY ("Id");


--
-- Name: PlaylistSongs PK_PlaylistSongs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistSongs"
    ADD CONSTRAINT "PK_PlaylistSongs" PRIMARY KEY ("Id");


--
-- Name: Playlists PK_Playlists; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Playlists"
    ADD CONSTRAINT "PK_Playlists" PRIMARY KEY ("Id");


--
-- Name: ScanSources PK_ScanSources; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ScanSources"
    ADD CONSTRAINT "PK_ScanSources" PRIMARY KEY ("Id");


--
-- Name: StorageCredentials PK_StorageCredentials; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StorageCredentials"
    ADD CONSTRAINT "PK_StorageCredentials" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: Plugins Plugins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Plugins"
    ADD CONSTRAINT "Plugins_pkey" PRIMARY KEY ("Id");


--
-- Name: TagEvidences TagEvidences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TagEvidences"
    ADD CONSTRAINT "TagEvidences_pkey" PRIMARY KEY ("Id");


--
-- Name: IX_EnrichmentAttempts_JobId_CreatedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EnrichmentAttempts_JobId_CreatedAt" ON public."EnrichmentAttempts" USING btree ("JobId", "CreatedAt");


--
-- Name: IX_EnrichmentJobs_Status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EnrichmentJobs_Status" ON public."EnrichmentJobs" USING btree ("Status");


--
-- Name: IX_Favorites_MediaFileId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Favorites_MediaFileId" ON public."Favorites" USING btree ("MediaFileId");


--
-- Name: IX_Favorites_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Favorites_UserId" ON public."Favorites" USING btree ("UserId");


--
-- Name: IX_MediaFiles_Album; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_Album" ON public."MediaFiles" USING btree ("Album");


--
-- Name: IX_MediaFiles_Artist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_Artist" ON public."MediaFiles" USING btree ("Artist");


--
-- Name: IX_MediaFiles_FilePath; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MediaFiles_FilePath" ON public."MediaFiles" USING btree ("FilePath");


--
-- Name: IX_MediaFiles_ScanSourceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_ScanSourceId" ON public."MediaFiles" USING btree ("ScanSourceId");


--
-- Name: IX_MediaIdentities_MediaFileId_Provider; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MediaIdentities_MediaFileId_Provider" ON public."MediaIdentities" USING btree ("MediaFileId", "Provider");


--
-- Name: IX_MediaIdentities_Provider_RecordingId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaIdentities_Provider_RecordingId" ON public."MediaIdentities" USING btree ("Provider", "RecordingId");


--
-- Name: IX_MediaTags_MediaFileId_Namespace_Key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_MediaTags_MediaFileId_Namespace_Key" ON public."MediaTags" USING btree ("MediaFileId", "Namespace", "Key");


--
-- Name: IX_MusicEnrichments_MediaFileId_CreatedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MusicEnrichments_MediaFileId_CreatedAt" ON public."MusicEnrichments" USING btree ("MediaFileId", "CreatedAt");


--
-- Name: IX_PlayHistories_MediaFileId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlayHistories_MediaFileId" ON public."PlayHistories" USING btree ("MediaFileId");


--
-- Name: IX_PlayHistories_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlayHistories_UserId" ON public."PlayHistories" USING btree ("UserId");


--
-- Name: IX_PlaylistSongs_MediaFileId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlaylistSongs_MediaFileId" ON public."PlaylistSongs" USING btree ("MediaFileId");


--
-- Name: IX_PlaylistSongs_PlaylistId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlaylistSongs_PlaylistId" ON public."PlaylistSongs" USING btree ("PlaylistId");


--
-- Name: IX_ScanSources_StorageCredentialId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ScanSources_StorageCredentialId" ON public."ScanSources" USING btree ("StorageCredentialId");


--
-- Name: IX_TagEvidences_MediaTagId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TagEvidences_MediaTagId" ON public."TagEvidences" USING btree ("MediaTagId");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username");


--
-- Name: Favorites FK_Favorites_MediaFiles_MediaFileId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_MediaFiles_MediaFileId" FOREIGN KEY ("MediaFileId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- Name: Favorites FK_Favorites_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: MediaFiles FK_MediaFiles_ScanSources_ScanSourceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "FK_MediaFiles_ScanSources_ScanSourceId" FOREIGN KEY ("ScanSourceId") REFERENCES public."ScanSources"("Id") ON DELETE CASCADE;


--
-- Name: PlayHistories FK_PlayHistories_MediaFiles_MediaFileId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlayHistories"
    ADD CONSTRAINT "FK_PlayHistories_MediaFiles_MediaFileId" FOREIGN KEY ("MediaFileId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- Name: PlayHistories FK_PlayHistories_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlayHistories"
    ADD CONSTRAINT "FK_PlayHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: PlaylistSongs FK_PlaylistSongs_MediaFiles_MediaFileId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistSongs"
    ADD CONSTRAINT "FK_PlaylistSongs_MediaFiles_MediaFileId" FOREIGN KEY ("MediaFileId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- Name: PlaylistSongs FK_PlaylistSongs_Playlists_PlaylistId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaylistSongs"
    ADD CONSTRAINT "FK_PlaylistSongs_Playlists_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES public."Playlists"("Id") ON DELETE CASCADE;


--
-- Name: ScanSources FK_ScanSources_StorageCredentials_StorageCredentialId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ScanSources"
    ADD CONSTRAINT "FK_ScanSources_StorageCredentials_StorageCredentialId" FOREIGN KEY ("StorageCredentialId") REFERENCES public."StorageCredentials"("Id");


--
-- Name: ScanSources FK_ScanSources_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ScanSources"
    ADD CONSTRAINT "FK_ScanSources_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


--
-- Name: StorageCredentials FK_StorageCredentials_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StorageCredentials"
    ADD CONSTRAINT "FK_StorageCredentials_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


--
-- Name: Lyrics Lyrics_MediaFileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lyrics"
    ADD CONSTRAINT "Lyrics_MediaFileId_fkey" FOREIGN KEY ("MediaFileId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
\unrestrict LCbKjUjoKzFdaFw9Cvf42E8OzxltTgSXKLqh8nc2OeLpDbDtCLSdNlEaaI2SvnR
